version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sibila_store
      MYSQL_USER: sibila
      MYSQL_PASSWORD: sibilapass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: sibila
      DB_PASSWORD: sibilapass
      DB_NAME: sibila_store
      DB_PORT: 3306
      PORT: 5000
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
